
import { project } from "../app/types/project";

export const HospitalItems: project[] = [
  {
    id: 1,
    category: "hospital",
    title: "Hospital Management",
    description: "Hospital Login",
    image: "assets/img/10.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "hospital",
    title: "Patient Registration",
    description: "New Patient Registration",
    image: "assets/img/7.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "hospital",
    title: "Patient List",
    description: "All Patient List",
    image: "assets/img/9.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "hospital",
    title: "Medicine",
    description: "List of All Medicine  ",
    image: "assets/img/8.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "hospital",
    title: "X-Ray",
    description: "Patient x-ray reports ",
    image: "assets/img/6.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "hospital",
    title: "Payment",
    description: "Payment Pannel",
    image: "assets/img/5.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "hospital",
    title: "Patient By Serial No.",
    description: "Find By SerialNo.  ",
    image: "assets/img/4.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "hospital",
    title: "Loan Application.",
    description: "Apply Loan App",
    image: "assets/img/3.png",
    detailsLink: "Link",
  },
  // {
  //   id: 9,
  //   category: "Product",
  //   title: "Dashboard",
  //   description: "Hospital Dashboard",
  //   image: "assets/img/2.png",
  //   detailsLink: "Link",
  // },
];

export const LabItems: project[] = [
  {
    id: 1,
    category: "Lab",
    title: "Lab Software",
    description: "Admin Login",
    image: "assets/img/10.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "Lab",
    title: "Patient Registration",
    description: "New Patient Registration",
    image: "assets/img/7.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "Lab",
    title: "Patient List",
    description: "All Patient List  ",
    image: "assets/img/9.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "Lab",
    title: "Medicine",
    description: "List of All Medicine  ",
    image: "assets/img/8.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "Lab",
    title: "X-Ray",
    description: "Patient x-ray reports ",
    image: "assets/img/6.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "Lab",
    title: "Payment",
    description: "Payment Pannel",
    image: "assets/img/5.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "Lab",
    title: "Patient By Serial No.",
    description: "Find By SerialNo.  ",
    image: "assets/img/4.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "Lab",
    title: "Loan Application.",
    description: "Apply Loan App",
    image: "assets/img/3.png",
    detailsLink: "Link",
  },
  {
    id: 9,
    category: "Lab",
    title: "Dashboard",
    description: "Hospital Dashboard",
    image: "assets/img/2.png",
    detailsLink: "Link",
  },
];

export const ApiUserAdminItems: project[] = [
  {
    id: 1,
    category: "Api",
    title: "Api Admin",  
    description: "Admin Dashbord",
    image: "assets/img/admindash.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "Api",
    title: "Api Admin",
    description: "Admin Fund Approve",
    image: "assets/img/adminFApprove.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "Api",
    title: "Api Admin",
    description: "Adnin Pin & Ipaddress",
    image: "assets/img/adminPin.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "Api",
    title: "Api User",
    description: "User Dashboard",
    image: "assets/img/userdashprofile.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "Api",
    title: "Api User",
    description: "Digital KYC ",
    image: "assets/img/digitalKYC.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "Api",
    title: "Api User",
    description: "User HelpDesk",
    image: "assets/img/userHelpDesk.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "Api",
    title: "Api User",
    description: "User Mobile View",
    image: "assets/img/userMobDash.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "Api",
    title: "Api User",
    description: "User Test Aadhar",
    image: "assets/img/userTestAadhar.png",
    detailsLink: "Link",
  },
  {
    id: 9,
    category: "Api",
    title: "Api User",
    description: "User Test Pan",
    image: "assets/img/userTestPan.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Test Crif",
    image: "assets/img/userHighmarkscore.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Test Equifax",
    image: "assets/img/userEquifaxScore.png",
    detailsLink: "Link",
  },
  {
    id: 10,
    category: "Api",
    title: "Api User",
    description: "User Lock Screen",
    image: "assets/img/userLock.png",
    detailsLink: "Link",
  },
];

export const InstituteItems: project[] = [
  {
    id: 1,
    category: "Preview",
    title: "Api User/Admin",
    description: "Admin Login",
    image: "assets/img/10.png",
    detailsLink: "Link",
  },
  {
    id: 2,
    category: "Product",
    title: "Patient Registration",
    description: "New Patient Registration",
    image: "assets/img/7.png",
    detailsLink: "Link",
  },
  {
    id: 3,
    category: "Product",
    title: "Patient List",
    description: "All Patient List  ",
    image: "assets/img/9.png",
    detailsLink: "Link",
  },
  {
    id: 4,
    category: "Product",
    title: "Medicine",
    description: "List of All Medicine  ",
    image: "assets/img/8.png",
    detailsLink: "Link",
  },
  {
    id: 5,
    category: "Product",
    title: "X-Ray",
    description: "Patient x-ray reports ",
    image: "assets/img/6.png",
    detailsLink: "Link",
  },
  {
    id: 6,
    category: "Product",
    title: "Payment",
    description: "Payment Pannel",
    image: "assets/img/5.png",
    detailsLink: "Link",
  },
  {
    id: 7,
    category: "Product",
    title: "Patient By Serial No.",
    description: "Find By SerialNo.  ",
    image: "assets/img/4.png",
    detailsLink: "Link",
  },
  {
    id: 8,
    category: "Product",
    title: "Loan Application.",
    description: "Apply Loan App",
    image: "assets/img/3.png",
    detailsLink: "Link",
  },
  {
    id: 9,
    category: "Product",
    title: "Dashboard",
    description: "Hospital Dashboard",
    image: "assets/img/2.png",
    detailsLink: "Link",
  },
];      